"""Centralized audit action names used across feature modules.

Dot-separated `{domain}.{action}` — not SCREAMING_SNAKE. Existing rows and
activity messages depend on this convention.

User-facing catalog names map here, e.g. ASSET_CREATED → `asset.create`.
"""


class AuditAction:
    AUTH_REGISTER = "auth.register"
    AUTH_LOGIN = "auth.login"
    AUTH_LOGIN_FAILED = "auth.login_failed"
    AUTH_ACCOUNT_LOCKED = "auth.account_locked"
    AUTH_ACCOUNT_DISABLED = "auth.account_disabled"
    AUTH_LOGOUT = "auth.logout"
    AUTH_REFRESH = "auth.refresh"
    AUTH_PASSWORD_CHANGE = "auth.password_change"
    AUTH_PASSWORD_RESET_REQUEST = "auth.password_reset_request"
    AUTH_PASSWORD_RESET = "auth.password_reset"
    AUTH_EMAIL_VERIFIED = "auth.email_verified"
    AUTH_SESSION_REVOKED = "auth.session_revoked"
    AUTH_SESSIONS_REVOKED_OTHERS = "auth.sessions_revoked_others"
    AUTH_SESSIONS_REVOKED_ALL = "auth.sessions_revoked_all"
    USER_PROFILE_UPDATE = "user.profile_update"
    ORG_UPDATE = "org.update"
    ORG_DELETE = "org.delete"
    ORG_CREATE = "org.create"
    ORG_CONFIG_CHANGED = "org.config_changed"
    ORG_RISK_SCORE_CHANGED = "org.risk_score_changed"
    ORG_MEMBER_INVITE = "org.member_invite"
    ORG_MEMBER_INVITE_REVOKE = "org.member_invite_revoke"
    ORG_MEMBER_ACCEPT = "org.member_accept"
    ORG_MEMBER_UPDATE = "org.member_update"
    ORG_MEMBER_REMOVE = "org.member_remove"
    ORG_OWNERSHIP_TRANSFER = "org.ownership_transfer"
    PROJECT_CREATE = "project.create"
    PROJECT_UPDATE = "project.update"
    PROJECT_DELETE = "project.delete"
    ASSET_CREATE = "asset.create"
    ASSET_UPDATE = "asset.update"
    ASSET_DELETE = "asset.delete"
    SCAN_CREATE = "scan.create"
    SCAN_RUN = "scan.run"
    SCAN_STARTED = "scan.started"
    SCAN_COMPLETED = "scan.completed"
    SCAN_FAILED = "scan.failed"
    SCAN_CANCEL = "scan.cancel"
    SCAN_PLUGIN_FAILED = "scan.plugin_failed"
    FINDING_UPDATE = "finding.update"
    FINDING_REVIEW = "finding.review"
    REPORT_CREATE = "report.create"
    REPORT_UPDATE = "report.update"
    REPORT_GENERATE = "report.generate"
    REPORT_REGENERATE = "report.regenerate"
    REPORT_DOWNLOAD = "report.download"
    REPORT_DELETE = "report.delete"
    AI_CHAT = "ai.chat"
    AI_CONVERSATION_STARTED = "ai.conversation_started"
    AI_EXPLANATION = "ai.explanation_requested"
    AI_REMEDIATION = "ai.remediation_generated"
    AI_SUMMARY = "ai.summary_generated"
    MONITORING_ENROLL = "monitoring.enroll"
    MONITORING_REGISTER = "monitoring.register"
    MONITORING_REVOKE = "monitoring.revoke"
    MONITORING_ALERT_OPENED = "monitoring.alert_opened"
    # Reserved until an API-key product surface exists.
    ADMIN_API_KEY_CREATED = "admin.api_key_created"
    ADMIN_API_KEY_REVOKED = "admin.api_key_revoked"
